install(DIRECTORY outline/plasma DESTINATION ${KDE_INSTALL_DATADIR}/${KWIN_DATADIR}/outline)
install(DIRECTORY onscreennotification/plasma DESTINATION ${KDE_INSTALL_DATADIR}/${KWIN_DATADIR}/onscreennotification)
install(DIRECTORY frames/plasma DESTINATION ${KDE_INSTALL_DATADIR}/${KWIN_DATADIR}/frames)
install(DIRECTORY ../tabbox/directswitcher DESTINATION ${KDE_INSTALL_DATADIR}/${KWIN_DATADIR}/tabbox)
install(DIRECTORY ../tabbox/directoverview DESTINATION ${KDE_INSTALL_DATADIR}/${KWIN_DATADIR}/tabbox)
